config/routes.rb
Lab3::Application.routes.draw do
  devise_for :users

	root :to => 'students#list', :id =>1 
  resources :students
	get 'students/list/:id', to: 'students#list', as: :list

	

end

app/models/student.rb
class Student < ActiveRecord::Base
attr_accessible :name, :studentid, :nickname, :finalgrade, :project1, :project2, :project3,
  :lab1,:lab2,:lab3,:lab4,:lab5,:lab6,:lab7, :class1,:class2,:class3,:class4,:class5,:class6,
  :class7,:class8,:class9,:class10

	validates :name, :studentid, :nickname, presence: true
	validates :studentid, numericality:{only_integer: true}
	validates :finalgrade,:project1, :project2, :project3,:lab1,:lab2,:lab3,:lab4,:lab5,:lab6,
	:lab7, :class1,:class2,:class3,:class4,:class5,:class6,:class7,:class8,:class9,:class10, presence: true
	validates :finalgrade, numericality: {
		only_integer: true,
		greater_than_or_equal_to: 0,
		less_than_or_equal_to: 100
}
	validates :project1, :project2, :project3,:lab1,:lab2,:lab3,:lab4,:lab5,:lab6,:lab7, 
	:class1,:class2,:class3,:class4,:class5,:class6,:class7,:class8,:class9,:class10 ,numericality: {
		only_integer: true,
		greater_than_or_equal_to: 0,
		less_than_or_equal_to: 100
}
		
		
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  def timeout_in
      10.minutes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

before_filter :authenticate_user!

  def list
    @len= Student.all.length
    @pid= (params[:id]).to_i
    @pnum= @pid*10
    a = Student.all.length
    @students = []
    allstu =[]
    i=1

    while a>0 do
      if Student.exists?(i)
        allstu=allstu+[Student.find(i)]
        a=a-1
        i=i+1
      else
        i=i+1
      end
    end
    

    if @len>=@pnum
      for k in 0..9 do
        @students=@students+[allstu[@pnum-10+k]]
      end
    else 
      for k in 0..@len+9-@pnum do
        @students=@students+[allstu[@pnum-10+k]]
      end
    end
  end

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to list_path(1), notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to list_path, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to list_url(1)}
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grading Worksheet</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    name<br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    student id<br />
    <%= f.text_field :studentid %>
  </div>
  <div class="field">
    nickname<br />
    <%= f.text_field :nickname %>
  </div>

  </br>
  <div style="color:red">
    Please value each item below with a grade from 0 to 100.
  </div>
  </br>

  <div class="project">
    <h3>Term Project(40%)</h3>
    <div class="field">
      iteration 1<br />
      <%= f.text_field :project1 %>%
    </div>
    <div class="field">
      iteration 2<br />
      <%= f.text_field :project2 %>%
    </div>
    <div class="field">
      iteration 3<br />
      <%= f.text_field :project3 %>%
    </div>
  </div>

  <div class="lab">
    <h3>Labs(10%)</h3>
    <div class="field">
      lab 1<br />
      <%= f.text_field :lab1 %>%
    </div>
    <div class="field">
      lab 2<br />
      <%= f.text_field :lab2 %>%
    </div>
    <div class="field">
      lab 3<br />
      <%= f.text_field :lab3 %>%
    </div>
    <div class="field">
      lab 4<br />
      <%= f.text_field :lab4 %>%
    </div>
    <div class="field">
      lab 5<br />
      <%= f.text_field :lab5 %>%
    </div>
    <div class="field">
      lab 6<br />
      <%= f.text_field :lab6 %>%
    </div>
    <div class="field">
      lab 7<br />
      <%= f.text_field :lab7 %>%
    </div>
  </div>

  <div class="final">
    <h3>Class Participations(10%)</h3>
    <div class="field">
      class 1<br />
      <%= f.text_field :class1 %>%
    </div>
    <div class="field">
      class 2<br />
      <%= f.text_field :class2 %>%
    </div>
    <div class="field">
      class 3<br />
      <%= f.text_field :class3 %>%
    </div>
    <div class="field">
      class 4<br />
      <%= f.text_field :class4 %>%
    </div>
    <div class="field">
      class 5<br />
      <%= f.text_field :class5 %>%
    </div>
    <div class="field">
      class 6<br />
      <%= f.text_field :class6 %>%
    </div>
    <div class="field">
      class 7<br />
      <%= f.text_field :class7 %>%
    </div>
    <div class="field">
      class 8<br />
      <%= f.text_field :class8 %>%
    </div>
    <div class="field">
      class 9<br />
      <%= f.text_field :class9 %>%
    </div>
    <div class="field">
      class 10<br />
      <%= f.text_field :class10 %>%
    </div>
  </div>

  <div class="class">
    <div class="field">
      <h3>Final Examination(40%)</h3>
      <%= f.text_field :finalgrade %>%
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>


<%= link_to 'Back', list_path(1) %>

app/views/students/index.html.erb
<head>
<script language="javascript">
function printdiv(printpage)
{
var headstr = "<html><head><title></title></head><body>";
var footstr = "</body>";
var newstr = document.all.item(printpage).innerHTML;
var oldstr = document.body.innerHTML;
document.body.innerHTML = newstr;
window.print();
document.body.innerHTML = oldstr;
return false;
}
</script>
</head>

<body>
<div id='div_print'>

<h1>Grading Worksheet</h1>
<table>
  <tr>
    <th>Student ID</th>
    <th>Student Name (Chinese)</th>
    <th>Nick Name (English)</th>
    <th>Project(40%)</th>
    <th>Final(40%)</th>
    <th>Lab(10%)</th>
    <th>Class(10%)</th>
    <th>Final</th>
  </tr>
<% @students.each do |student| %>

  <tr>
    <td><%= student.studentid %></td>
    <td><%= student.name %></td>
    <td><%= student.nickname %></td>
    <td><%= 0.4*(student.project1*0.25+student.project1*0.25+student.project1*0.5) %>%</td>
    <td><%= 0.4*student.finalgrade %>%</td>
    <td><%= 0.1/7*(student.lab1+student.lab2+student.lab3+student.lab4+student.lab5+student.lab6+student.lab7) %>%</td>
    <td><%= 0.01*(student.class1+student.class2+student.class3+student.class4+student.class5+student.class6+student.class7+student.class8+student.class9+student.class10) %>%</td>
    <td><%= 0.4*(student.project1*0.25+student.project1*0.25+student.project1*0.5)+0.4*student.finalgrade+0.1/7*(student.lab1+student.lab2+student.lab3+student.lab4+student.lab5+student.lab6+student.lab7)+0.01*(student.class1+student.class2+student.class3+student.class4+student.class5+student.class6+student.class7+student.class8+student.class9+student.class10) %>%</td>
  </tr>
<% end %>
</table>

</div>

<br />
<table>
  <tr>
    <td id="butt"></td>
    <td><%= link_to 'Back', list_path(1) %></td>
    <td><input align="right" name="b_print" type="button" class="ipt" onClick="printdiv('div_print');" value=" Print "> </td>
  </tr>
</table>
</body>

app/views/students/list.html.erb
<h1>Grading Worksheet</h1>
<table>
  <tr>
    <th>Student ID</th>
    <th>Student Name (Chinese)</th>
    <th>Nick Name (English)</th>
    <th>Project(40%)</th>
    <th>Final(40%)</th>
    <th>Lab(10%)</th>
    <th>Class(10%)</th>
    <th>Final</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @students.each do |student| %>

  <tr>
    <td><%= student.studentid %></td>
    <td><%= student.name %></td>
    <td><%= student.nickname %></td>
    <td><%= 0.4*(student.project1*0.25+student.project1*0.25+student.project1*0.5) %>%</td>
    <td><%= 0.4*student.finalgrade %>%</td>
    <td><%= 0.1/7*(student.lab1+student.lab2+student.lab3+student.lab4+student.lab5+student.lab6+student.lab7) %>%</td>
    <td><%= 0.01*(student.class1+student.class2+student.class3+student.class4+student.class5+student.class6+student.class7+student.class8+student.class9+student.class10) %>%</td>
    <td><%= 0.4*(student.project1*0.25+student.project1*0.25+student.project1*0.5)+0.4*student.finalgrade+0.1/7*(student.lab1+student.lab2+student.lab3+student.lab4+student.lab5+student.lab6+student.lab7)+0.01*(student.class1+student.class2+student.class3+student.class4+student.class5+student.class6+student.class7+student.class8+student.class9+student.class10) %>%</td>
    
    <td><%= link_to 'Edit', edit_student_path(student) %>
    
    <%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
  <tr>
    <td><br/><%= link_to 'New Student', new_student_path %></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></br>
        <% if @pnum<@len %>
            <%= link_to 'Next', list_path(@pid+1) %>
        <% end %></td>
    <td></br>
        <% if @pid>1 %>
            <%= link_to 'Previous', list_path(@pid-1) %>
        <% end %></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td><input id="btnClose" type="button" value="Exit" onClick="custom_close()" /></td>
    <td><%= link_to 'Print', students_path %></td>
    <td></br></td>
    <td></td>
  </tr>
</table>

<script language="javascript">
function custom_close(){
if 
(confirm("Are you sure to exit？")){
window.opener=null;
window.open('','_self');
window.close();
}
else{}
}
</script>

 <% if current_user %>
       <%= link_to('log out', destroy_user_session_path, :method => :delete) %> |
     <%= link_to('change password', edit_registration_path(:user)) %>
   <% else %>
      <%= link_to('sign in', new_registration_path(:user)) %> |
        <%= link_to('log in', new_session_path(:user)) %>
   <% end %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', list_path(1) %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2>Name:</h2>
  <%= @student.name %>
</p>
<p>
  <h2>Student ID:</h2>
  <%= @student.studentid %>
</p>
<p>
  <h2>Nick Name:</h2>
  <%= @student.nickname %>
</p>
<div class="project">
  <h2>Term Project(40%):</h2>
  <div><b>project 1</b><br>
  <%= @student.project1 %>%
  </div>
  <div><b>project 2</b><br>
  <%= @student.project2 %>%
  </div>
  <div><b>project 3</b><br>
  <%= @student.project3 %>%
  </div>
</div>
<div class="lab">
  <h2>Labs(10%):</h2>
  <div><b>lab 1</b><br>
  <%= @student.lab1 %>%
  </div>
  <div><b>lab 2</b><br>
  <%= @student.lab2 %>%
  </div>
  <div><b>lab 3</b><br>
  <%= @student.lab3 %>%
  </div>
  <div><b>lab 4</b><br>
  <%= @student.lab4 %>%
  </div>
  <div><b>lab 5</b><br>
  <%= @student.lab5 %>%
  </div>
  <div><b>lab 6</b><br>
  <%= @student.lab6 %>%
  </div>
  <div><b>lab 7</b><br>
  <%= @student.lab7 %>%
  </div>
</div>
<div class="project">
  <h2>Class Participations(10%)</h2>
  <div><b>class 1</b><br>
  <%= @student.class1 %>%
  </div>
  <div><b>class 2</b><br>
  <%= @student.class2 %>%
  </div>
  <div><b>class 3</b><br>
  <%= @student.class3 %>%
  </div>
  <div><b>class 4</b><br>
  <%= @student.class4 %>%
  </div>
  <div><b>class 5</b><br>
  <%= @student.class5 %>%
  </div>
  <div><b>class 6</b><br>
  <%= @student.class6 %>%
  </div>
  <div><b>class 7</b><br>
  <%= @student.class7 %>%
  </div>
  <div><b>class 8</b><br>
  <%= @student.class8 %>%
  </div>
  <div><b>class 9</b><br>
  <%= @student.class9 %>%
  </div>
  <div><b>class 10</b><br>
  <%= @student.class10 %>%
  </div>
</div>


</p>
  <h2>final:</h2>
  <%= @student.finalgrade %>%
</br>



<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', list_path(1) %>